# Site settings
title: Nicholas Mutsaerts
description: Microsoft 365 Administration | Tier 2 IT Support | Windows, macOS & Linux
description: Welcome to my IT portfolio and knowledge base

show_downloads: false
theme: jekyll-theme-cayman

github:
  is_project_page: false

