# Site settings
title: Nicholas Mutsaerts
description: System Administrator | Tier 2 IT Support | Windows, macOS & Microsoft 365

show_downloads: false
theme: jekyll-theme-cayman

github:
  is_project_page: false

